create_gif:
  name: Create GIF
  description: Create a GIF from a list of images
  fields:
    images:
      name: Images
      description: List of image file paths
      required: true
      example: ["/config/images/image1.jpg", "/config/images/image2.jpg"]
    fps:
      name: FPS
      description: Frames per second for the GIF
      required: false
      default: 10
      example: 10
    output_path:
      name: Output Path
      description: Path to save the GIF
      required: true
      example: "/config/gifs/output.gif"
